// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAYQeSwG0eSmMYFDBMHmH9B9WsqOn73XU',
    appId: '1:999154670463:web:a34ba132b2afa1a1f6d84a',
    messagingSenderId: '999154670463',
    projectId: 'swasearch-project',
    authDomain: 'swasearch-project.firebaseapp.com',
    storageBucket: 'swasearch-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARmygplJdfFsfXht_BQc7HBkVbjlDB8gI',
    appId: '1:999154670463:android:46a6ffac1355c5d0f6d84a',
    messagingSenderId: '999154670463',
    projectId: 'swasearch-project',
    storageBucket: 'swasearch-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtqMRVkt0jexuQHgo98TIoEkKIUDyYy54',
    appId: '1:999154670463:ios:7ea9e8f339011d89f6d84a',
    messagingSenderId: '999154670463',
    projectId: 'swasearch-project',
    storageBucket: 'swasearch-project.appspot.com',
    iosClientId: '999154670463-tileen7pe6g8t5o39u1jheas0nfraamv.apps.googleusercontent.com',
    iosBundleId: 'com.example.swasearch',
  );
}
